[General]
daemonAddress=localhost
daemonPort=11987
daemonSSLEnabled=true
networkCookies="@ByteArray(cc=duGGY6aV7hYqydjVDxzGe/HQMeDTC3hvppr8oUMgXxwiFhw+zSMG2PbFktynMcZZTDc=; HttpOnly; expires=Sat, 30-May-2026 18:12:52 GMT; domain=localhost; path=/\n)"
windowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\ai\0\0\x3\xf4\0\0\0\0\0\0\0\0\0\0\ai\0\0\x3\xf4\0\0\0\0\0\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\ai\0\0\x3\xf4)
